name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the bug...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of ClipPAilot are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows 11
        - Windows 10
        - Other (specify in additional info)
    validations:
      required: true
  - type: dropdown
    id: downloads
    attributes:
      label: Download Type
      description: What kind of download were you trying?
      options:
        - Video (MP4)
        - Video (Other format)
        - Audio (MP3)
        - Audio (Other format)
        - Not related to downloads
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
